---
# 设置 kubeconfig 文件
  # 使用 ansible 的 file 模块来确保 /root/.kube/ 目录已经存在，若该目录不存在则创建
  - name: Ensure that the /root/.kube/ directory exits
    file:
      path: /root/.kube
      state: directory
  
  # 使用 ansible 的 copy 模块将 kubeconfig 文件从 /etc/kubernetes/admin.conf 
  # 复制到默认的位置 /root/.kube/config
  # 目的是为了能够更方便地使用 kubectl 命令行工具来管理 Kubernetes 集群，
  # 因为 kubectl 默认会查找 /root/.kube/config 文件来获取连接集群所需的信息。
  - name: Copy the kubeconfig to the default location
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      # TODO 为什么要设置为 yes
      remote_src: yes